<?xml version="1.0" ?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
  <xacro:macro name="wheel" params="name diameter right">
    <link name="${name}_wheel">
      <inertial>
        <mass value="0.2"/>
        <origin rpy="0 1.5707 1.5707" xyz="0 0 0"/>
        <inertia ixx="0.000526666666667" ixy="0" ixz="0" iyy="0.000526666666667" iyz="0" izz="0.001"/>
      </inertial>
      <collision>
        <origin rpy="0 1.5707 1.5707" xyz="0 0 0"/>
        <geometry>
          <cylinder length="0.04" radius="${diameter/2}"/>
        </geometry>
      </collision>
      <visual>
        <origin rpy="0 1.5707 1.5707" xyz="0 0 0"/>
        <geometry>
          <cylinder length="0.04" radius="${diameter/2}"/>
        </geometry>
      </visual>
    </link>
    <joint name="joint_${name}_wheel" type="continuous">
      <xacro:if value="${right == 1}">
        <origin rpy="0 0 0" xyz="-0.15 -0.15 0" />
      </xacro:if>
      <xacro:if value="${right == 0}">
        <origin rpy="0 0 0" xyz="-0.15 0.15 0" />
      </xacro:if>
      <child link="${name}_wheel"/>
      <parent link="chassis"/>
      <axis rpy="0 0 0" xyz="0 1 0"/>
      <limit effort="10000" velocity="1000"/>
      <joint_properties damping="1.0" friction="1.0"/>
    </joint>
  </xacro:macro>
</robot>